config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  resources :users, only: [:create]
  resource :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :blogs, except: [:new]
    resources :logs, except: [:new]
    resources :shoes, only: [:index, :create, :destroy, :edit]
    resources :users, only: [:index, :show, :update]
    resources :follows, only: [:create, :destroy]
    resources :searches, only: [:index]
    resources :comments, only: [:create]
  end

  get "/auth/:provider/callback", to: "sessions#omniauth"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag '/favicon.ico' %>

  <title>Runlogr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="page-header">

    <nav class="header-nav group">
      <h1 class="header-logo"><a class="group" href="#feed"><p class="run">run<p class="logr">logr</p></a></h1>
      <% if logged_in? %>
      <li class="user-search-header"><a href="#search">Search Users</a></li>
      <ul class="header-user group">
        <section class="header-chunk">
          <li><a href="#blogs/new">Add Blog</a></li>
          <li><a href="#logs/new">Add Log</a></li>
        </section>

        <li class="header-chunk header-profile-pic">
          <a href="#users/<%= current_user.id.to_s %>">
            <img src="<%= current_user.profile_pic(:feed) %>" alt="<%= current_user.username %>" />
          </a>
        </li>
        <section class="header-chunk">

          <li>
            <form class="log-out" action="<%= sessions_url %>" method="POST">
              <input type="hidden" name="_method" value="DELETE">
              <%= auth_token %>
              <button>Log Out</button>
            </form>
          </li>
          <li>
            <a href="#users/<%= current_user.id.to_s %>"><%= current_user.username %></a>
          </li>
        </section>
      </ul>
      <% end %>
    </nav>
  </header>

  <%= yield %>

  <footer class="page-footer">
    <nav class="footer-nav group">
      <p>
        Created by  <a href="http://www.paulbanel.com" target="_blank">Paul Banel</a>, 2015.
        Background photo by <a href="http://www.lauracasner.com/#" target="_blank">Laura Casner</a>.
      </p>
    </nav>
  </footer>
</body>
</html>